# Generated by Django 5.2.3 on 2025-11-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hangman",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("words", models.TextField()),
                ("category", models.TextField()),
                ("clue_1", models.TextField()),
                ("clue_2", models.TextField()),
                ("clue_3", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
